dbp_relay_core:
#  keycloak_client_id: '%env(KEYCLOAK_FRONTEND_CLIENT_ID)%'
  build_info: '%env(APP_BUILDINFO)%'
  build_info_url: '%env(APP_BUILDINFO_URL)%'
  docs_title:       'KRAKEN Education Pilot - Uni API Backend'
  docs_description: '*[API](https://github.com/krakenh2020/EduPilotBackend) for a [frontend](https://github.com/krakenh2020/EduPilotFrontend) that provides education verifiable credentials to university students.*'
