name: Build, Deploy

on:
 push:
   branches:
     - master
 workflow_dispatch:
   branches:
     - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Generate demo keys
        run: cd docker-dev && ./generate_demo_keys.sh
      -
        name: Install PHP Dependencies
        run: cd docker-dev && bash build.sh
      - 
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker Build & Push Frontend image
        run: |
          export DOCKER_TAG=docker.pkg.github.com/krakenh2020/edupilotbackend/kraken-edu_frontend:latest
          echo "Building branch: $GITHUB_REF"
          echo "      at commit: ${{ github.sha }}"
          echo "   triggered by: ${{ github.event_name}}"
          echo "     Pushing to: $DOCKER_TAG"
          docker build . --tag $DOCKER_TAG --file Dockerfile.nginx
          docker push $DOCKER_TAG
      -
        name: Docker Build & Push PHP image
        run: |
          export DOCKER_TAG=docker.pkg.github.com/krakenh2020/edupilotbackend/kraken-edu_php:latest
          echo "Building branch: $GITHUB_REF"
          echo "      at commit: ${{ github.sha }}"
          echo "   triggered by: ${{ github.event_name}}"
          echo "     Pushing to: $DOCKER_TAG"
          docker build . --tag $DOCKER_TAG --file Dockerfile.php
          docker push $DOCKER_TAG
          
