name: docker-ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Install PHP Dependencies
        run: cd docker-dev && bash build.sh
      -
        name: Build and push nginx image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.nginx
          push: false
          tags: krakenh2020/EduPilotBackend/kraken-edu_frontend:latest
      -
        name: Build and push PHP image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.php
          push: false
          tags: krakenh2020/EduPilotBackend/kraken-edu_php:latest
