name: Test GitHub actions containers
# https://docs.github.com/en/actions/using-containerized-services/about-service-containers

on:
 push:
   branches:
     - master
 workflow_dispatch:
   branches:
     - main

jobs:
  containerexperiments:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create helper containers
        run: |
          docker pull ghcr.io/hyperledger/aries-framework-go:0.1.6
          docker network create --label kraken-network github_network_kraken
          docker create --name student-agent-container --label student-agent --network github_network_kraken --network-alias student-agent -p 8092:8092 -p 8091:8091  -e "ARIESD_API_HOST=0.0.0.0:8092" -e "ARIESD_INBOUND_HOST=http@0.0.0.0:8091" -e "ARIESD_INBOUND_HOST_EXTERNAL=http@http://student-agent:8091" -e "ARIESD_WEBHOOK_URL=https://enybebk8mydni.x.pipedream.net" -e "ARIESD_DEFAULT_LABEL=student-agent" -e "ARIESD_DATABASE_TYPE=leveldb" -e "ARIESD_DATABASE_PREFIX=student" -e "ARIESD_DATABASE_TIMEOUT=60" -e "ARIESD_HTTP_RESOLVER=sidetree@http://sidetree-mock.demo:48326/sidetree/0.0.1/identifiers" -e GITHUB_ACTIONS=true -e CI=true ghcr.io/hyperledger/aries-framework-go:0.1.6 start
          docker start student-agent-container

      -
        name: Show service logs
        continue-on-error: true
        run: |
          docker ps
          docker logs "student-agent-container"

      -
        name: Test via localhost
        continue-on-error: true
        run: |
          curl http://localhost:8092/connections

      -
        name: Test via 127.0.0.1
        continue-on-error: true
        run: |
          curl http://127.0.0.1:8092/connections

      -
        name: Test via hostname
        continue-on-error: true
        run: |
          curl http://student-agent:8092/connections
